[build]
  command = "npm run build"
  publish = "dist"  # build를 dist로 변경

[[redirects]]
  from = "/api/*"
  to = "http://aengmung.tplinkdns.com:8010/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200